### ISSUE TITLE
Padrão para contribuição

### ISSUE THREAD

**Issue by osvaldoabel** [omarkdev/awesome-talks#1]
Tem algúm padrão para contribuição ?
Seria legal colocar no Readme, um "como contribuir" ou algo do tipo. (para o pessoal não ficar perdiro)
o que acha, @omarkdev

**Comment by omarkdev** [comment]
Interessante, vou criar um CONTRIBUTING.md para isso, mas creio que não terá muito conteúdo já que não estamos seguindo nenhum padrão para contribuição por enquanto. Mas obrigado pela sugestão.

**Comment by osvaldoabel** [comment]
certo, @omarkdev . 
não precisa Criar um arquivo só para isso. 
mas podia especificar (se os commits serão só em inglês, pt, se tem que ter quantos Commits por PR , sei lá rsrs o importante é começar já certo. afinal, a tendência é o projeto crescer)
